### ISSUE TITLE
MultiScaleDeformableAttention ImportError

### ISSUE THREAD

**Issue by sheeranshan** [mlpc-ucsd/PRTR#1]
(PRTR) hpe2020@hbuzntw002-Precision-7920-Tower:~/shanbg/PRTR/two_stage$ python tools/test.py     --cfg experiments/coco/transformer/w32_384x288_adamw_lr1e-4.yaml     TEST.MODEL_FILE models/pytorch/pose_coco/pose_transformer_w32_384x288.pth     TEST.USE_GT_BBOX False
Traceback (most recent call last):
  File "tools/test.py", line 26, in <module>
    from models.matcher import build_matcher
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/__init__.py", line 14, in <module>
    import models.deformable_pose_transformer
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/deformable_pose_transformer.py", line 5, in <module>
    from models.deformable_transformer import build_deformable_transformer, inverse_sigmoid
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/deformable_transformer.py", line 19, in <module>
    from models.ops.modules import MSDeformAttn
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/ops/modules/__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/ops/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/hpe2020/shanbg/PRTR/two_stage/tools/../lib/models/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/hpe2020/anaconda3/envs/PRTR/lib/python3.6/site-packages/MultiScaleDeformableAttention-1.0-py3.6-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

I need help

**Comment by zx1239856** [comment]
Hi

Please modify this line
https://github.com/mlpc-ucsd/PRTR/blob/a09f772af200ffee7264e87c5883d99f5e81452a/two_stage/lib/models/__init__.py#L15
as
```python
except (ModuleNotFoundError, ImportError) as ex:
```

to make it capture the `ImportError` here. Running legacy Transformer does not require `DeformableAttention` module.

However, if you want to try out `DeformableTranformer`, this could still be a problem. Please specify the environment where you use our code. (PyTorch, CUDA, Python version, etc.)

**Comment by sheeranshan** [comment]
> Hi
> 
> Please modify this line
> https://github.com/mlpc-ucsd/PRTR/blob/a09f772af200ffee7264e87c5883d99f5e81452a/two_stage/lib/models/__init__.py#L15
> 
> 
> as
> ```python
> except (ModuleNotFoundError, ImportError) as ex:
> ```
> 
> to make it capture the `ImportError` here. Running legacy Transformer does not require `DeformableAttention` module.
> 
> However, if you want to try out `DeformableTranformer`, this could still be a problem. Please specify the environment where you use our code. (PyTorch, CUDA, Python version, etc.)

thanks,

and can i test my pictures with this program?

**Comment by zx1239856** [comment]
You can do inference on your own dataset. Prior to this, you need to provide person bounding boxes since the dataset loader requires them to crop the original image.
